spring.application.name=Mirai-Api
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/mirai_db
spring.datasource.username=postgres
spring.datasource.password=donlito123

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.contentnegotiation.media-types.xlsx = application/vnd.openxmlformats-officedocument.spreadsheetml.sheet



